name = "threadsiq-cron"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/5 * * * *"]   # Every 5 minutes

[[kv_namespaces]]
binding = "THREADSIQ_STORE"
id = "a5ce9c7ba11149f99c2cfe3ec63f1a8b"

[[d1_databases]]
binding = "THREADSIQ_DB"
database_name = "threadsiq"
database_id = "1e02d028-a720-4d7c-b7b7-0aaa279959f9"

[vars]
APP_URL = "https://threads-iq.pages.dev"
